# Uncomment the next line to define a global platform for your project
platform :ios, '14.5'

target 'MichiEki' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MichiEki
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'

end

target 'MichiEkiTests' do
  pod 'RxBlocking', '6.2.0'
  pod 'RxTest', '6.2.0'

end